# Generated by Django 3.1.1 on 2020-09-25 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=100)),
                ('building_address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ITInventory',
            fields=[
                ('asset_tag', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('asset_description', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('class_details', models.CharField(max_length=100)),
                ('stwd_last_name', models.CharField(max_length=30)),
                ('stwd_first_name', models.CharField(max_length=30)),
                ('last_inventory_date', models.DateField()),
                ('accqusation_date', models.DateField()),
                ('cost', models.FloatField()),
                ('model_details', models.CharField(max_length=500)),
                ('serial_number', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('building', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory_app.building')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.department')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.manufacturer')),
            ],
        ),
    ]
