# Generated by Django 3.1.1 on 2020-10-10 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=100)),
                ('building_address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_type', models.CharField(max_length=100)),
                ('dept_building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.building')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=500)),
                ('vendor_email', models.CharField(default='', max_length=500)),
                ('vendor_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Steward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stwd_name', models.CharField(max_length=500)),
                ('stwd_email', models.CharField(max_length=500)),
                ('stwd_buidling_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.building')),
                ('stwd_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.room')),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=500)),
                ('model_manufacturer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='ITInventory',
            fields=[
                ('asset_tag', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('asset_description', models.CharField(blank=True, max_length=50)),
                ('class_details', models.CharField(max_length=100)),
                ('last_inventory_date', models.DateField()),
                ('accqusation_date', models.DateField()),
                ('cost', models.FloatField()),
                ('serial_number', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('buildingID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory_app.building')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.category')),
                ('departmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.department')),
                ('manufacturerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.manufacturer')),
                ('model_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.models')),
                ('room', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory_app.room')),
                ('stwd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.steward')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.vendor')),
            ],
        ),
    ]
