# Generated by Django 3.1.1 on 2020-10-13 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_building_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.building'),
        ),
    ]
