# Generated by Django 3.1.1 on 2020-10-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_email',
            field=models.CharField(default='', max_length=500),
        ),
    ]
