# Generated by Django 3.1.1 on 2020-09-30 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinventory',
            name='asset_description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='itinventory',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itinventory',
            name='building',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='inventory_app.building'),
        ),
    ]
