# Generated by Django 3.1.1 on 2020-10-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_auto_20200930_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinventory',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
    ]
