# Generated by Django 3.1.1 on 2020-10-05 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_itinventory_export_to_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinventory',
            name='export_to_CSV',
        ),
    ]
